### ISSUE TITLE
Compatability with pg:backups

### ISSUE THREAD

**Issue by JoshSmith** [kjohnston/pgbackups-archive#46]
The old `pgbackups` addon has been deprecated. Is this gem compatible with the new `pg:backups`?

I'm having trouble because the `PGBACKUPS_URL` is not defined.

**Comment by kjohnston** [comment]
I've got a [spike](https://github.com/kjohnston/pgbackups-archive/compare/pg-backups-conversion?expand=1) going to convert to the `pg:backups` style.  It works great if you're logged into the Toolbelt, but it doesn't magically work without logging in within a Heroku environment as `pgbackups` does.

There are custom buildpacks that you can add that allow you to login to the Toolbelt if you store credentials in environment variables, but that's lame.  Hoping to find another way around.  Open to ideas.

**Comment by kjohnston** [comment]
Good news - v1.0.0 is out now with support for the new [Heroku PGBackups](https://devcenter.heroku.com/articles/heroku-postgres-backups) service.  The deprecated [PG Backups](https://devcenter.heroku.com/articles/pgbackups) add-on is no longer supported.  Upgrade will be mandatory for everyone - as soon as Heroku finishes shutting off the old service (their announcement from the other day mentioned ~2 weeks).

There are some environment variable changes to be mindful of - please review the readme and your env vars for each app you're using this for.

I was confused earlier - simply storing an API key in the `HEROKU_API_KEY` environment variable circumvents the need to store a user's username and use a custom buildpack to authenticate via the Toolbelt.  /cc @kbaum 

Another thing I realized is that while the documentation for the new [Heroku PGBackups](https://devcenter.heroku.com/articles/heroku-postgres-backups) says that you can still pass `--expire` to the `capture` command manually, this does not seem to work.  So, v1.0.0 of this gem handles expiration of the oldest backup on the Heroku side for you.

**Comment by JoshSmith** [comment]
Really excellent work @kjohnston. I owe you a :beer:
