### ISSUE TITLE
Bump or remove direct heroku gem dependency due to CVE warnings

### ISSUE THREAD

**Issue by mikeatlas** [kjohnston/pgbackups-archive#49]
Per the latest (double) indirect CVE warnings, your gem also depends on a vulnerable `rest-client` version. See https://github.com/heroku/heroku/pull/1470

You may want to wait and see what they do, or consider wrapping the CLI app commands instead maybe (ick, but... what are you gonna do?)

**Comment by dickeyxxx** [comment]
yeah (unfortunately) the CLI really isn't intended to be included like this. It can cause issues with things like having different gem version requirements, or if the user wants to use something like jruby (which the toolbelt doesn't support). It might be best to just shell out to the toolbelt and expect the user to have it installed.

**Comment by kjohnston** [comment]
Thanks guys.  I pushed v1.0.1 which loosens the `heroku` gem version required - it just has to be anything greater than the version at which we moved to the new Heroku PGBackups service (over the older add-on).  So, when Heroku merges https://github.com/heroku/heroku/pull/1470 and pushes a new version, you can switch to that.

This gem currently depends heavily on the `heroku` gem's internals.  Shelling out to the Heroku CLI could work, but I'm not a fan of that approach.  I really just wish that the Heroku PGBackups API was something that we could reach out and talk to, without going through the Toolbelt / deprecated gem.
