### ISSUE TITLE
PGBACKUPS_APP in file path

### ISSUE THREAD

**Issue by caifara** [kjohnston/pgbackups-archive#57]
Could you use the app name (PGBACKUPS_APP in the file path? (here: https://github.com/kjohnston/pgbackups-archive/blob/master/lib/pgbackups-archive/job.rb#L98, preferably in second position).
It makes it possible to have a central backup bucket (I would use that because I have several deployments of the same app, all running in production).

**Comment by kjohnston** [comment]
#56 has this change staged.  I'll check on status over there.

**Comment by caifara** [comment]
ah, missed that. Feel free to close … I'll follow #56
