### ISSUE TITLE
ReadMe update

### ISSUE THREAD

**Issue by michaelimstepf** [kjohnston/pgbackups-archive#59]
Awesome gem, thanks for creating this. The link to the pro tip on how to create a policy seems to contain outdated information (i.e. the policy format is no longer valid), here's the policy that worked for us:

```javascript
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-name"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-name/*"
            ]
        }
    ]
}
```

Also, the heroku command to add the scheduler add-on has changed to: 
```
heroku addons:create scheduler:standard
```

**Comment by kjohnston** [comment]
Thanks for bringing these items up.

I updated the protip - it pretty much matches what you have here (minus the "s3:GetObject" permission, which isn't required.

I updated the readme entry for the schedule addon as well.

Thanks!
