### ISSUE TITLE
NameError: uninitialized constant Heroku::JSPlugin

### ISSUE THREAD

**Issue by homerjon** [kjohnston/pgbackups-archive#61]
When I run 

heroku run rake pgbackups:archive --trace --account myaccount -a myappname

I get the following error.

Running `rake pgbackups:archive --trace` attached to terminal... up, run.9289
** Invoke pgbackups:archive (first_time)
** Execute pgbackups:archive
rake aborted!
NameError: uninitialized constant Heroku::JSPlugin

/app/vendor/bundle/ruby/1.9.1/gems/heroku-3.39.4/lib/heroku/command.rb:22:in `load'
/app/vendor/bundle/ruby/1.9.1/gems/pgbackups-archive-1.0.2/lib/pgbackups-archive/job.rb:16:in `initialize'
/app/vendor/bundle/ruby/1.9.1/gems/pgbackups-archive-1.0.2/lib/pgbackups-archive/job.rb:12:in `new'
/app/vendor/bundle/ruby/1.9.1/gems/pgbackups-archive-1.0.2/lib/pgbackups-archive/job.rb:12:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/pgbackups-archive-1.0.2/lib/tasks/pgbackups_archive.rake:5:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/app/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/app/vendor/bundle/ruby/1.9.1/bin/rake:23:in `load'
/app/vendor/bundle/ruby/1.9.1/bin/rake:23:in `<main>'
Tasks: TOP => pgbackups:archive

Any thoughts?

**Comment by homerjon** [comment]
GEMFILE

source 'http://rubygems.org'
ruby '1.9.3'
gem 'rails', '3.2.11'
gem 'rake'   
group :development do
  gem 'mysql2', '0.3.11'
end
   
gem 'pg'
gem 'rails_12factor'
gem 'devise' 
gem 'tabs_on_rails'
gem 'will_paginate'
gem 'cancan'
gem 'nested_has_many_through'
gem 'acts_as_list'
gem 'squeel'
gem 'ransack'
gem 'high_voltage'
gem 'paperclip', '~> 3.4.1'
gem 'fastercsv'
gem 'aws-sdk'
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'heroku'
gem 'heroku-api'
gem 'json', '~> 1.8.0'
gem 'resque'
gem 'bcrypt-ruby', '~> 3.0.1', :require => 'bcrypt'
gem 'rack', '1.4.0' 
gem 'hirefire-resource'
gem 'httparty'
gem 'doc_raptor'

group :assets do
  gem 'sass-rails', '  ~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'

gem "pgbackups-archive"



GEMFILE.LOCK

GEM
  remote: http://rubygems.org/
  specs:
    actionmailer (3.2.11)
      actionpack (= 3.2.11)
      mail (~> 2.4.4)
    actionpack (3.2.11)
      activemodel (= 3.2.11)
      activesupport (= 3.2.11)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.0)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.2.1)
    activemodel (3.2.11)
      activesupport (= 3.2.11)
      builder (~> 3.0.0)
    activerecord (3.2.11)
      activemodel (= 3.2.11)
      activesupport (= 3.2.11)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.11)
      activemodel (= 3.2.11)
      activesupport (= 3.2.11)
    activesupport (3.2.11)
      i18n (~> 0.6)
      multi_json (~> 1.0)
    acts_as_list (0.4.0)
      activerecord (>= 3.0)
    addressable (2.3.8)
    arel (3.0.3)
    aws-sdk (1.50.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    bcrypt (3.1.7)
    bcrypt (3.1.7)
    bcrypt-ruby (3.0.1)
    bcrypt-ruby (3.0.1)
    builder (3.0.4)
    cancan (1.6.10)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.4)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.7.1)
    delayed_job (4.0.2)
      activesupport (>= 3.0, < 4.2)
    delayed_job_active_record (4.0.1)
      activerecord (>= 3.0, < 4.2)
      delayed_job (>= 3.0, < 4.1)
    devise (3.2.4)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    doc_raptor (0.3.2)
      httparty (>= 0.7.0)
    domain_name (0.5.24)
      unf (>= 0.0.5, < 1.0.0)
    erubis (2.7.0)
    excon (0.45.3)
    execjs (2.2.1)
    fastercsv (1.5.5)
    ffi (1.9.10)
    ffi (1.9.10)
    fog-aws (0.7.3)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (1.32.0)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    formatador (0.2.5)
    heroku (3.39.4)
      heroku-api (>= 0.3.19)
      launchy (>= 0.3.2)
      multi_json (>= 1.10)
      netrc (>= 0.10.0)
      rest-client (>= 1.6.0)
      rubyzip (>= 0.9.9)
    heroku-api (0.3.23)
      excon (~> 0.44)
      multi_json (~> 1.8)
    high_voltage (2.2.1)
    hike (1.2.3)
    hirefire-resource (0.3.4)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    httparty (0.13.1)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.6.11)
    ipaddress (0.8.0)
    journey (1.0.4)
    jquery-rails (3.1.1)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (4.1.2)
      railties (>= 3.1.0)
    json (1.8.3)
    launchy (2.4.3)
      addressable (~> 2.3)
    mail (2.4.4)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.25.1)
    mini_portile (0.6.0)
    mono_logger (1.1.0)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    mysql2 (0.3.11)
    mysql2 (0.3.11)
    nested_has_many_through (0.0.2)
      rails (>= 3.0.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    netrc (0.10.3)
    nokogiri (1.6.3.1)
      mini_portile (= 0.6.0)
    nokogiri (1.6.3.1)
      mini_portile (= 0.6.0)
    orm_adapter (0.5.0)
    paperclip (3.4.2)
      activemodel (>= 3.0.0)
      activerecord (>= 3.0.0)
      activesupport (>= 3.0.0)
      cocaine (~> 0.5.0)
      mime-types
    pg (0.17.1)
    pg (0.17.1)
    pgbackups-archive (1.0.2)
      fog-aws
      heroku (>= 3.28.6)
      rake
    polyamorous (1.0.0)
      activerecord (>= 3.0)
    polyglot (0.3.5)
    rack (1.4.0)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-protection (1.5.3)
      rack
    rack-ssl (1.3.4)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (3.2.11)
      actionmailer (= 3.2.11)
      actionpack (= 3.2.11)
      activerecord (= 3.2.11)
      activeresource (= 3.2.11)
      activesupport (= 3.2.11)
      bundler (~> 1.0)
      railties (= 3.2.11)
    rails_12factor (0.0.2)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.2)
    rails_stdout_logging (0.0.3)
    railties (3.2.11)
      actionpack (= 3.2.11)
      activesupport (= 3.2.11)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    rake (10.3.2)
    ransack (1.2.3)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.0.0)
    rdoc (3.12.2)
      json (~> 1.4)
    redis (3.2.1)
    redis-namespace (1.5.1)
      redis (~> 3.0, >= 3.0.4)
    resque (1.25.2)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.3)
      sinatra (>= 0.9.2)
      vegas (~> 0.1.2)
    rest-client (1.8.0)
      ffi (~> 1.9)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rest-client (1.8.0)
      ffi (~> 1.9)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rubyzip (1.1.7)
    sass (3.3.14)
    sass-rails (3.2.6)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    sinatra (1.4.5)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    sprockets (2.2.2)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    squeel (0.8.9)
      activerecord (~> 3.0)
      activesupport (~> 3.0)
    tabs_on_rails (2.2.0)
    thor (0.19.1)
    thread_safe (0.3.4)
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (0.3.40)
    uglifier (2.5.3)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    unf_ext (0.0.7.1)
    vegas (0.1.11)
      rack (>= 1.0.0)
    warden (1.2.3)
      rack (>= 1.0)
    will_paginate (3.0.7)

PLATFORMS


DEPENDENCIES
  acts_as_list
  aws-sdk
  bcrypt-ruby (~> 3.0.1)
  cancan
  coffee-rails (~> 3.2.1)
  delayed_job
  delayed_job_active_record
  devise
  doc_raptor
  fastercsv
  heroku
  heroku-api
  high_voltage
  hirefire-resource
  httparty
  jquery-rails
  jquery-ui-rails
  json (~> 1.8.0)
  mysql2 (= 0.3.11)
  nested_has_many_through
  paperclip (~> 3.4.1)
  pg
  pgbackups-archive
  rack (= 1.4.0)
  rails (= 3.2.11)
  rails_12factor
  rake
  ransack
  resque
  sass-rails (~> 3.2.3)
  squeel
  tabs_on_rails
  uglifier (>= 1.0.3)
  will_paginate

**Comment by kjohnston** [comment]
Looks like you're using `heroku` 3.39.4 as a result of simply listing `heroku` with no version specification in your Gemfile.  `pgbackups-archive` requires a `heroku` version between 3.28.6 and 3.32.0.

Most apps can get away without listing the `heroku` gem in their Gemfile, however, I see that you're also using `heroku-api`, so perhaps you have some version negotiation to do.

The `heroku` gem project has been moving really fast lately, despite its deprecation.  Currently, there are no plans to support 3.33+.
