### ISSUE TITLE
Issue running heroku run rake pgbackups:archive -a myapp

### ISSUE THREAD

**Issue by ctoynbee** [kjohnston/pgbackups-archive#62]
I'm not sure if this is a problem with my heroku configuration but when I run the rake task to test it using:

heroku run rake pgbackups:archive -a myapp

I get:

Running `rake pgbackups:archive` attached to terminal... up, run.3069
rake aborted!
URI::InvalidURIError: bad URI(is not URI?):
/app/vendor/bundle/ruby/2.1.0/gems/heroku-3.9.1/lib/heroku/client/pgbackups.rb:9:in `initialize'

Has anyone else had that issue?

**Comment by theinventor** [comment]
+1

**Comment by luxxi** [comment]
Update to the latest version 1.0.3 and change environment variables.
