### ISSUE TITLE
Where do you get the collaborator api key?

### ISSUE THREAD

**Issue by simkessy** [kjohnston/pgbackups-archive#65]
I can't figure out where this would be? 

heroku config:add HEROKU_API_KEY="collaborator-api-key"

**Comment by warrenchaudhry** [comment]
**heroku auth:token**

**Comment by bitops** [comment]
This page has the information - https://devcenter.heroku.com/articles/platform-api-quickstart

You just log in to the Heroku dashboard and it'll be under your Account page.
