### ISSUE TITLE
Support for Google Storage

### ISSUE THREAD

**Issue by KelseyDH** [kjohnston/pgbackups-archive#66]
I used to use the `heroku_cloud_storage` gem for backups to s3 and Google Storage, but that gem has since been abandoned and no longer works due to the change in Heroku's backup api.  This gem looks promising but it does not appear to support backups to Google Storage.  Would the authors of this gem be interested in having it also support backups to Google Storage?

You can find their implementation of Google Storage backups here:  https://github.com/kamui/heroku_cloud_backup/blob/master/lib/heroku_cloud_backup.rb#L68

**Comment by kjohnston** [comment]
While I don't have plans to add support to this gem for other storage providers, if you do use it to push to S3 you can setup a Transfer in Google Cloud Storage to replicate from an S3 bucket to a Google Cloud Storage bucket automatically on a daily basis.
