### ISSUE TITLE
Error requiring rake task in README for non-rails apps

### ISSUE THREAD

**Issue by subelsky** [kjohnston/pgbackups-archive#67]
btw I had to put this in my Rakefile:

```
require "pgbackups-archive"
load "tasks/pgbackups_archive.rake"
```

mainly writing this in case others come across this issue -- happy to submit a PR to either make the load statement unnecessary OR fix the README. Let me know if/how you'd like me to handle this. Thanks for the gem!

PS rationale for this is I made a separate standalone app to handle backups; I don't like putting this stuff into web-facing apps where possible

**Comment by thomasdavis** [comment]
@subelsky Thanks for this! Would have taken me forever to debug.
