### ISSUE TITLE
deprecated heroku gem

### ISSUE THREAD

**Issue by jrr** [kjohnston/pgbackups-archive#68]
```
Post-install message from heroku:
 !    The `heroku` gem has been deprecated and replaced with the Heroku Toolbelt.
 !    Download and install from: https://toolbelt.heroku.com
 !    For API access, see: https://github.com/heroku/heroku.rb
```

https://blog.heroku.com/archives/2012/10/15/upgrading-to-the-heroku-toolbelt

**Comment by darinwilson** [comment]
Has there been any more work done on switching to Heroku toolbelt? It appears that v2 of the API (and therefore the gem) will stop working on Apr 15:

https://blog.heroku.com/sunsetting_heroku_s_legacy_platform_api_v2

**Comment by kjohnston** [comment]
This gem is still latching onto a version range of the `heroku` gem that uses the v3 API.  Going the toolbelt route involves heading a different direction and some dependencies, for a good solution see [heroku-database-backups](https://github.com/kbaum/heroku-database-backups).

**Comment by darinwilson** [comment]
@kjohnston Thanks for the quick response. It was my mistake - we were using an older version of the gem, and I missed that. Sorry to trouble you! :)
