### ISSUE TITLE
Backups failing during Heroku API sunset brownout

### ISSUE THREAD

**Issue by xtagon** [kjohnston/pgbackups-archive#70]
Hi,

Heroku is sunsetting their old API version, and right now they are performing a 1-hour brownout to help uncover cases that will break when the API is really sunset. Turns out pgbackups-archive might be one such breakage.

I manually ran `bundle exec rake pgbackups:archive` on my app, intending to test it during this brownout, and it failed with the following errors:

```
rake aborted!
Heroku::API::Errors::ErrorWithResponse: Expected(200) <=> Actual(410 Gone)

body: "{\"id\":\"gone\",\"error\":\"This version of the API has been Sunset.\\nPlease see https://devcenter.heroku.com/changelog-items/1147 for more information.\\n\"}"
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:388:in `response'
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:252:in `request'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-api-0.3.23/lib/heroku/api.rb:83:in `request'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/auth.rb:20:in `request'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-api-0.3.23/lib/heroku/api/attachments.rb:6:in `get_attachments'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/helpers/heroku_postgresql.rb:99:in `app_attachments'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/helpers/heroku_postgresql.rb:104:in `hpg_databases'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/helpers/heroku_postgresql.rb:159:in `hpg_resolve'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/helpers/heroku_postgresql.rb:58:in `resolve'
/app/vendor/bundle/ruby/2.4.0/gems/pgbackups-archive-1.1.0/lib/pgbackups-archive/job.rb:35:in `capture'
/app/vendor/bundle/ruby/2.4.0/gems/pgbackups-archive-1.1.0/lib/pgbackups-archive/job.rb:22:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/pgbackups-archive-1.1.0/lib/pgbackups-archive/job.rb:12:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/pgbackups-archive-1.1.0/lib/tasks/pgbackups_archive.rake:5:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bugsnag-5.2.0/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
/app/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Excon::Error::Gone: Expected(200) <=> Actual(410 Gone)

body: "{\"id\":\"gone\",\"error\":\"This version of the API has been Sunset.\\nPlease see https://devcenter.heroku.com/changelog-items/1147 for more information.\\n\"}"
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:388:in `response'
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:252:in `request'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-api-0.3.23/lib/heroku/api.rb:83:in `request'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/auth.rb:20:in `request'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-api-0.3.23/lib/heroku/api/attachments.rb:6:in `get_attachments'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/helpers/heroku_postgresql.rb:99:in `app_attachments'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/helpers/heroku_postgresql.rb:104:in `hpg_databases'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/helpers/heroku_postgresql.rb:159:in `hpg_resolve'
/app/vendor/bundle/ruby/2.4.0/gems/heroku-3.32.0/lib/heroku/helpers/heroku_postgresql.rb:58:in `resolve'
/app/vendor/bundle/ruby/2.4.0/gems/pgbackups-archive-1.1.0/lib/pgbackups-archive/job.rb:35:in `capture'
/app/vendor/bundle/ruby/2.4.0/gems/pgbackups-archive-1.1.0/lib/pgbackups-archive/job.rb:22:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/pgbackups-archive-1.1.0/lib/pgbackups-archive/job.rb:12:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/pgbackups-archive-1.1.0/lib/tasks/pgbackups_archive.rake:5:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bugsnag-5.2.0/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
/app/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Tasks: TOP => pgbackups:archive
(See full trace by running task with --trace)
```

I'm running version 1.1.0 of pgbackups-archive. What needs to happen to fix this?

Thanks! :-)

**Comment by daniely** [comment]
I really appreciate the work that went into pgarchives-backup and used it for awhile. But until there's a fix for the sunsetting of the heroku-api I'm looking into https://github.com/kbaum/heroku-database-backups.

**Comment by xtagon** [comment]
@daniely Can you confirm that that one works with the new Heroku API changes? For something like database backups one can't afford to just wait and hope for a fix this critical.

**Comment by daniely** [comment]
@xtagon I'm working on adding it today but haven't finished yet. Here's some relevant info from a [blog post](http://stefan.haflidason.com/automatic-off-site-backups-for-your-heroku-postgres-databases/). Emphasis mine:

> A quick search online will bring you to the promising-looking pgbackups-archive project. Set up a few environment variables and you’re done. **Unfortunately, due to Heroku deprecating the heroku gem in favour of the Heroku Toolbelt, this project is probably not what you want to use any more**, which is a shame as it will have received the most testing out of the options available to us.
> 
> We will instead use the newer heroku-database-backups project, which is a standalone Heroku app that we will configure to capture and archive our production database(s). As it is based on the recommended tools of each platform (the Heroku Toolbelt and the Universal Command Line Interface for AWS) then **we can perhaps reasonably expect that this approach will not break any time soon**, though we would be foolish to rely on that.

**Comment by kjohnston** [comment]
This gem's approach to piggybacking on the old `heroku` gem (AKA [Legacy CLI](https://github.com/heroku/legacy-cli)) which uses the [Legacy Platform API (v2)](https://legacy-api-docs.herokuapp.com/) that is [being sunset](https://blog.heroku.com/sunsetting_heroku_s_legacy_platform_api_v2) will cease to function when that API is no longer available.

[heroku-database-backups](https://github.com/kbaum/heroku-database-backups) is a good alternative to this gem that leverages the officially supported Heroku CLI + Platform API and AWS CLI.

I'll leave this issue open for a bit for others to navigate to.  I'll update the readme in the near future - and might reference other lightweight alternative solutions, feel free to comment here if you've implemented something worth sharing.

**Comment by daniely** [comment]
@kjohnston would it be possible to use https://github.com/heroku/platform-api instead of the `heroku` gem?

**Comment by kjohnston** [comment]
@daniely from what I can tell the Platform API doesn't offer an endpoint to retrieve backup download URLs.

**Comment by daniely** [comment]
@kjohnston looks like you are correct: https://github.com/heroku/platform-api/issues/72

**Comment by daniely** [comment]
@xtagon I moved everything over to heroku-database-backups and it's working great.

Not quite as easy to setup as pgbackups-archive was. But the nice thing is you can have one heroku app responsible for backing up multiple databases (even from different heroku apps).

**Comment by xtagon** [comment]
@daniely Thanks for the tip! So the separate app will not require a running dyno, you'll only pay for the scheduled task's one-off dyno time, yes?

**Comment by daniely** [comment]
@xtagon that sounds right. I expect that amazon s3 is the only thing that will cost anything.

**Comment by xtagon** [comment]
@daniely Any update on this? Do you happen to have a fork of either this project or heroku-database-backups that supports the new API now? Thanks :)

**Comment by daniely** [comment]
@xtagon heroku-database-backups has always worked with the new API.

**Comment by xtagon** [comment]
@daniely When I tried it, I was getting API deprecation warnings in the logs. But I switched it to use the official platform API buildpack instead of https://github.com/gregburek/heroku-buildpack-toolbelt.git and it works great!

**Comment by daniely** [comment]
@xtagon I don't know if I'm misunderstanding you but that's the first step in the instructions :)

`heroku create my-database-backups --buildpack https://github.com/heroku/heroku-buildpack-multi`

**Comment by xtagon** [comment]
@daniely That's to set the buildpack as the multi-buildpack. The actual buildpack it uses is defined in the `.buildpacks` file. See here: https://github.com/kbaum/heroku-database-backups/blob/master/.buildpacks

It's set to `https://github.com/gregburek/heroku-buildpack-toolbelt.git` but that buildpack is deprecated. So I changed it to https://github.com/heroku/heroku-buildpack-cli and updated the commands to match
